
function psi=StaticPot2(a,L,rho,z)

% psi=StaticPot2(a,L,rho,z,m) calculates electrostatic potential psi 
% generated by a constant charge density on a cylinder of circular 
% cross section in free space (vacuum), with unit total charge on it. 
% L is the cylinder height, a its radius, rho and z are the cylindrical 
% coordinates of the observation point. It is assumed that the cylinder 
% axis extends from the origin to the point z=L along the z-axis.
% Input arguments must be scalars.

RelAcc=1e-8;  % relative accuracy

global IntPara_n IntPara_1 IntPara_2 IntPara_L IntPara_z

% normalization parameter roughly estimating result,
% used for proper tolerance handling:

IntPara_n=StaticPot1(L,rho,z);

if a==0,
  psi=IntPara_n;
  return
end

IntPara_1=rho.^2+a.^2;
IntPara_2=2.*rho.*a;
IntPara_L=L;
IntPara_z=z;

% integrate:

psi=quadml(@IntegrandStaticPot2,0,2*pi,RelAcc)*IntPara_n/(2*pi);
%psi=quadl(@IntegrandStaticPot2,0,2*pi,RelAcc)*IntPara_n/(2*pi);


end % of main function


% -------------------------------------

function pot=IntegrandStaticPot2(phi)

global IntPara_n IntPara_1 IntPara_2 IntPara_L IntPara_z

rhox=sqrt(IntPara_1-IntPara_2.*cos(phi));
pot=StaticPot1(IntPara_L,rhox,IntPara_z)/IntPara_n;

end






