	SUBROUTINE CLLINE(X1,Y1,X2,Y2)
C
C	THIS SUBROUTINE DRAWS THE LINE FROM X1,Y1 TO X2,Y2 WITH
C	THE APPROPIATE CLIPPING
C
C
	DIMENSION AREA(4)
C
	CALL MPCLIP(AREA)
	CALL SCALE(X1,Y1,VX,VY)
	CALL GSMOVE(VX,VY)
	CALL SCALE(X2,Y2,VX,VY)
	CALL GSDRAW(VX,VY)
	CALL GSRCLP(AREA)
	RETURN
	END
