	SUBROUTINE CURVE(X,Y,NPTS,ISYMNO,SYMSIZ,NPBSYM)
	DIMENSION X(NPTS), Y(NPTS)
C
C	THIS SUBROUTINE TRACES THE LINE FROM X(1),Y(1) TO
C	X(NPTS),Y(NPTS) WITH APPROPIATE CLIPPING.
C	IT THEN ADDS THE DESIRED SYMBOL (ISYMNO) TO THE PLOT SPACED
C	"NPBSYM" POINTS APART.
C
	DIMENSION AREA(4)
C
	CALL MPCLIP(AREA)
	CALL SCALE(X(1),Y(1),VX,VY)
	CALL GSMOVE(VX,VY)
	IF (NPTS .LE. 1) GO TO 110
10	DO 100 I=2,NPTS
	CALL SCALE(X(I),Y(I),VX,VY)
	CALL GSDRAW(VX,VY)
100	CONTINUE
C
C	NOW ADD SYMBOLS IF DESIRED
C
110	CONTINUE
	IF (ISYMNO .EQ. 0) GO TO 800
C
C	ADD THE SYMBOLS
C
	DO 200 I=1, NPTS, NPBSYM
		CALL SCALE(X(I),Y(I),VX,VY)
		CALL GSMOVE(VX,VY)
		CALL SYMBOL(ISYMNO,SYMSIZ)
200		CONTINUE
800	CONTINUE
	CALL GSRCLP(AREA)
	RETURN
	END
