	SUBROUTINE GDAID(X,Y,XGUPCM,YGUPCM,IX,IY)
C
	IX = XGUPCM*X + 0.5
	IY = YGUPCM*Y + 0.5
	RETURN
	END
	SUBROUTINE GDGAID(IX,IY,XGUPCM,YGUPCM,X,Y)
C
	X = FLOAT(IX)/XGUPCM
	Y = FLOAT(IY)/YGUPCM
	RETURN
	END
