	SUBROUTINE GDWAIT(MILLISECONDS)
C
C	THIS SUBROUTINE DELAYS A GIVEN NUMBER OF MILLISECONDS.
C
C<>VMS	INTEGER*4 SYS$SETIMR,SYS$WAITFR
C
C<>VMS	INTEGER*4 DELTIME(2)
C
C<>VMS	DELTIME(1) = -MILLISECONDS*10000 !10,000 (100ns) UNITS PER MILLISEC.
C<>VMS	DELTIME(2) = -1
C<>VMS	ISTAT = SYS$SETIMR(%VAL(1),DELTIME, , )
C<>VMS	IF (.NOT. ISTAT) STOP 'SET TIME FAILURE'
C<>VMS	ISTAT = SYS$WAITFR(%VAL(1))
C<>VMS	IF (.NOT. ISTAT) STOP 'WAITFOR FAILURE'
C
C	Since we only have resolution to the second on Unix, round up
C	to the next second.
C
	ISEC = INT( (MILLISECONDS+999.0) / 1000.0 )
	CALL SLEEP( ISEC )
	RETURN
	END
