	SUBROUTINE GSINPT(X,Y,LFLAG,IERR)
	LOGICAL LFLAG
C
C	DO A GENERIC GRAPHICS INPUT
C
	CHARACTER*1 CHAR, SPACE
	DATA SPACE /' '/
C
	CALL GSCRSR(X,Y,IBUTN,IERR)
	IF (IERR .NE. 0) GO TO 100
		LFLAG = (IAND(IBUTN,1) .EQ. 1)
		RETURN
100	CONTINUE
	CALL GSGIN(X,Y,CHAR,IERR)
	IF (IERR .NE. 0) RETURN
	LFLAG = (CHAR .EQ. SPACE)
	RETURN
	END
