	SUBROUTINE MINMAX(ARRAY,NPTS,BMIN,BMAX)
C
C	FIND MINIMUM AND MAXIMUM OF THE ARRAY
C
	DIMENSION ARRAY(NPTS)
	BMIN = ARRAY(1)
	BMAX = BMIN
	DO 100 I=2,NPTS
	BMIN = AMIN1(BMIN,ARRAY(I))
100	BMAX = AMAX1(BMAX,ARRAY(I))
	RETURN
	END
