	SUBROUTINE POINTC(X,Y,NPTS)
	DIMENSION X(NPTS), Y(NPTS)
C
C	THIS SUBROUTINE PLOTS THE VISIBLE POINTS ON THE SCREEN
C
	DIMENSION AREA(4)
C
	CALL MPCLIP(AREA)
	DO 100 I=1,NPTS
	CALL SCALE(X(I),Y(I),VX,VY)
	CALL GSMOVE(VX,VY)
	CALL SYMBOL(3,0.3)
100	CONTINUE
	CALL GSRCLP(AREA)
	RETURN
	END
