	SUBROUTINE POINTS(X,Y,NPTS)
C
C	THIS SUBROUTINE IS USED TO PLOT POINTS ON THE SCREEN
C
	DIMENSION X(NPTS),Y(NPTS)
	DO 100 I=1, NPTS
	CALL SCALE(X(I),Y(I),VX,VY)
	CALL GSMOVE(VX,VY)
100	CALL SYMBOL(3,0.3)
	RETURN
	END
