	SUBROUTINE TRACCY(XMIN,XMAX,Y,NPTS)
	DIMENSION Y(NPTS)
C
C	THIS SUBROUTINE TRACES THE LINE FROM X(1),Y(1) TO
C	X(NPTS),Y(NPTS) WITH APPROPIATE CLIPPING.
C	USE THIS ROUTINE WHEN CLIPPING IS DESIRED AND THE
C	INDEPENDANT VARIABLE IS IMPLIED BY THE SUBSCRIPT
C	USING EQUAL INTERVALS FROM XMIN TO XMAX.
C
	DIMENSION AREA(4)
C
	CALL MPCLIP(AREA)
	CALL SCALE(XMIN,Y(1),VX,VY)
	CALL GSMOVE(VX,VY)
10	DX = (XMAX-XMIN)/(NPTS-1)
	DO 100 I=2,NPTS
	CALL SCALE(XMIN+(I-1)*DX,Y(I),VX,VY)
	CALL GSDRAW(VX,VY)
100	CONTINUE
	CALL GSRCLP(AREA)
	RETURN
	END
