	SUBROUTINE TRACE(X,Y,NPTS)
C
C	THIS SUBROUTINE IS USED TO PLOT DATA ON THE SCREEN AS
C	A CONTINOUS LINE.
C
	DIMENSION X(2), Y(2)
	CALL SCALE(X(1),Y(1),VX,VY)
	CALL GSMOVE(VX,VY)
	DO 100 I=2,NPTS
	CALL SCALE(X(I),Y(I),VX,VY)
100	CALL GSDRAW(VX,VY)
	RETURN
	END
