	SUBROUTINE TRACEY(XMIN,XMAX,Y,NPTS)
C
C	THIS SUBROUTINE IS USED TO PLOT DATA ON THE SCREEN AS
C	A CONTINOUS LINE, GIVEN ONLY THE Y ARRAY AND XMIN AND XMAX.
C
	DIMENSION Y(2)
	CALL SCALE(XMIN,Y(1),VX,VY)
	CALL GSMOVE(VX,VY)
	XINC = (XMAX-XMIN)/(NPTS-1)
	X = XMIN
	DO 100 I=2,NPTS
	X = X + XINC
	CALL SCALE(X,Y(I),VX,VY)
100	CALL GSDRAW(VX,VY)
	RETURN
	END
