
function mpsi=Interact11(r1,r2,r3,r4)

% mpsi=Interact11(r1,r2,r3,r4)
% Calculates mean voltage on a segment from r3 to t4,
% as generated by a segment from r1 to r2 which
% is uniformly charges with total charge 1.

global Interact11_IntPara_r3 Interact11_IntPara_r34 Interact11_IntPara_e12 
global Interact11_IntPara_L Interact11_IntPara_n

RelAcc=1e-5;

Interact11_IntPara_r3=r3(:).'-r1(:).';
Interact11_IntPara_r34=r4(:).'-r3(:).';
Interact11_IntPara_e12=r2(:)-r1(:);
Interact11_IntPara_L=sqrt(sum(Interact11_IntPara_e12.^2));
Interact11_IntPara_e12=Interact11_IntPara_e12/Interact11_IntPara_L;

r=(r3(:)+r4(:)).'/2;
z=r*Interact11_IntPara_e12;
rho=sqrt(max(0,sum(r.^2,2)-z.^2));

Interact11_IntPara_n=StaticPot1(Interact11_IntPara_L,rho,z);

mpsi=quadml(@Interact11Integrand,0,1,RelAcc)*Interact11_IntPara_n;

end


function psi=Interact11Integrand(t)

global Interact11_IntPara_r3 Interact11_IntPara_r34 Interact11_IntPara_e12 
global Interact11_IntPara_L Interact11_IntPara_n

r=repmat(Interact11_IntPara_r3,length(t),1)+t(:)*Interact11_IntPara_r34;

z=r*Interact11_IntPara_e12;
rho=sqrt(max(0,sum(r.^2,2)-z.^2));

psi=reshape(StaticPot1(Interact11_IntPara_L,rho,z)/Interact11_IntPara_n,size(t));

end

