
function mpsi=Interact33(r1,r2,r3,ra,rb,rc)

% mpsi=Interact31(r1,r2,r3,ra,rb)
% Calculates mean voltage on a triangle with corners (ra,rb,rc),
% as generated by the triangle with the corners (r1,r2,r3) which
% is uniformly charges with total charge 1.

global Interact33_IntPara_r1 Interact33_IntPara_r2 Interact33_IntPara_r3
global Interact33_IntPara_ra Interact33_IntPara_rab Interact33_IntPara_rac 
global Interact33_IntPara_n

RelAcc=1e-5;

Interact33_IntPara_r1=r1(:).';
Interact33_IntPara_r2=r2(:).';
Interact33_IntPara_r3=r3(:).';
Interact33_IntPara_ra=ra(:).';
Interact33_IntPara_rab=rb(:).'-ra(:).';
Interact33_IntPara_rac=rc(:).'-ra(:).';

Interact33_IntPara_n=StaticPot3(...
  Interact33_IntPara_r1,Interact33_IntPara_r2,Interact33_IntPara_r3,...
  (rc(:)+rb(:)+ra(:)).'/3);

mpsi=quadml(@Interact33Integrand,0,1,RelAcc)*2*Interact33_IntPara_n;

end


function psi=Interact33Integrand(t)

global Interact33_IntPara_r1 Interact33_IntPara_r2 Interact33_IntPara_r3
global Interact33_IntPara_ra Interact33_IntPara_rab Interact33_IntPara_rac 
global Interact33_IntPara_n

nn=numel(t);

rt1=repmat(Interact33_IntPara_ra,nn,1)+t(:)*Interact33_IntPara_rab;
rt2=rt1+(1-t(:))*Interact33_IntPara_rac;

psi=zeros(size(t));

for n=1:nn,
  psi(n)=Interact31(...
    Interact33_IntPara_r1,Interact33_IntPara_r2,Interact33_IntPara_r3,...
    rt1(n,:),rt2(n,:))*(1-t(n))/Interact33_IntPara_n;
end

end

