
function mpsi=Interact31(r1,r2,r3,ra,rb)

% mpsi=Interact31(r1,r2,r3,ra,rb)
% Calculates mean voltage on a segment from ra to rb,
% as generated by the triangle with the corners (r1,r2,r3) which
% is uniformly charges with total charge 1.

global Interact31_IntPara_r1 Interact31_IntPara_r2 Interact31_IntPara_r3
global Interact31_IntPara_ra Interact31_IntPara_rab Interact31_IntPara_n

RelAcc=1e-5;

Interact31_IntPara_r1=r1(:).';
Interact31_IntPara_r2=r2(:).';
Interact31_IntPara_r3=r3(:).';
Interact31_IntPara_ra=ra(:).';
Interact31_IntPara_rab=rb(:).'-ra(:).';

Interact31_IntPara_n=StaticPot3(...
  Interact31_IntPara_r1,Interact31_IntPara_r2,Interact31_IntPara_r3,...
  (rb(:)+ra(:)).'/2);

mpsi=quadml(@Interact31Integrand,0,1,RelAcc)*Interact31_IntPara_n;

end


function psi=Interact31Integrand(t)

global Interact31_IntPara_r1 Interact31_IntPara_r2 Interact31_IntPara_r3
global Interact31_IntPara_ra Interact31_IntPara_rab Interact31_IntPara_n

nn=numel(t);

r=repmat(Interact31_IntPara_ra,nn,1)+t(:)*Interact31_IntPara_rab;

psi=zeros(size(t));

for n=1:nn,
  psi(n)=StaticPot3(...
    Interact31_IntPara_r1,Interact31_IntPara_r2,Interact31_IntPara_r3,r(n,:))/...
    Interact31_IntPara_n;
end

end

